Ading files and folders
TiteLunda/Portofolio_Mob pull request #3
Opened 2023-03-02 05:41 UTC by TiteLunda

Contact form added to the mob version portofolio project

2023-03-02 17:48 UTC, TiteLunda commented
![image](https://user-images.githubusercontent.com/98431708/222509956-facea176-a0f5-4144-9a3d-d5006e4a7f57.png)
I attached this screenshot as proof allowing me to do projects this week solo.

2023-03-02 19:19 UTC, hiromataba requested changes
Hi @TiteLunda    :wave: :wave: 

![almost-there](https://user-images.githubusercontent.com/75126481/160092588-b3f37e8e-a1d9-4b14-84fc-7ec1fed7b3e5.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Your PR has a proper title and description  :+1: 
- Your linters are passing :heavy_check_mark:  
- Profesional README file :rocket: 

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-02 19:19 UTC, hiromataba commented on index.html
> +                <div class="inputs">
- [ ] You should use formspree service to collect data of your form and your form should have a post method 

![image](https://user-images.githubusercontent.com/75126481/222521333-06f53530-0110-4e83-be33-b73f93250b96.png)

2023-03-02 19:19 UTC, hiromataba commented on index.html
> +                    </button>
- [ ]. Your button should have submit as type in order to submit the form

2023-03-02 19:19 UTC, hiromataba commented on index.html
> +            </h1>
- [ ] Please check my feedback from [ the video](https://youtu.be/Dmm04Kyzpyg) I recorded for you

2023-03-03 13:34 UTC, frank1738 approved these changes
Hi @TiteLunda , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/tIeCLkB8geYtW/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ Form submission is working fine👍 

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-03 13:37 UTC, merged